---
services:

  db:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [CMD, pg_isready, -U, postgres, -d, postgres, -q]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/sql:/docker-entrypoint-initdb.d

  test-db-tools:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uv run pytest

  generate-default-db:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uv run python -m fushigi_backend.tools_main
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
      test-db-tools:
        condition: service_completed_successfully

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    command:
      - uv
      - run
      - uvicorn
      - fushigi_backend.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
    working_dir: /app/backend
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules

  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

volumes:
  pg_data:
