---
services:

  db:
    build:
      context: .
      dockerfile: pocketbase/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:8080/api/health]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    volumes:
      - pb_data:/pb/pb_data

  test-db-tools:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uv run pytest

  generate-default-db:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uv run python -m fushigi_backend.tools_main
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
      test-db-tools:
        condition: service_completed_successfully

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    command:
      - uv
      - run
      - uvicorn
      - fushigi_backend.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
    working_dir: /app/backend
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      VITE_API_BASE: "http://backend:8000"
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src:cached
      - ./frontend/static:/app/static:cached
      - ./frontend/components.json:/app/components.json:cached
      - ./frontend/svelte.config.js:/app/svelte.config.js:cached
      - ./frontend/vite.config.ts:/app/vite.config.ts:cached
      - ./frontend/tsconfig.json:/app/tsconfig.json:cached

volumes:
  pb_data:
