services:

  db:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [CMD, pg_isready, -U, postgres, -d, postgres, -q]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    volumes:
        - pg_data:/var/lib/postgresql/data
        - ./db-tools/sql:/docker-entrypoint-initdb.d
  
  test-db-tools:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./db-tools:/app/db-tools
    working_dir: /app/db-tools
    command: uv run pytest

  generate-default-db:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./db-tools:/app/db-tools
    working_dir: /app/db-tools
    command: uv run python -m fushigi_db_tools.main
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
      test-db-tools:
        condition: service_completed_successfully
   
  backend:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: uv run uvicorn fushigi_backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 5173:5173
    command: bun --bun run dev --host 0.0.0.0
    volumes:
      - ./app:/app

  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

volumes:
  pg_data:
