---
services:

  db:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:8090/api/health]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SMTP_USERNAME: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      PB_ENCRYPTION_KEY: ${PB_ENCRYPTION_KEY}
    ports:
      - 8090:8090
    volumes:
      - pb_data:/pb/pb_data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: http://localhost:8090
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src:cached
      - ./frontend/static:/app/static:cached
      - ./frontend/components.json:/app/components.json:cached
      - ./frontend/svelte.config.js:/app/svelte.config.js:cached
      - ./frontend/vite.config.ts:/app/vite.config.ts:cached
      - ./frontend/tsconfig.json:/app/tsconfig.json:cached

volumes:
  pb_data:
