[tool.uv.sources]
fushigi-db-tools = { workspace = true }

[tool.uv.workspace]
members = ["backend"]

# TODO: taplo
[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
pythonpath = ["."]
#testpaths = ["tests"] -- determined automatically from folder its run in

[tool.hatch.build]
include = ["fushigi_backend/**"]
