[project]
name = "fushigi-backend"
version = "0.1.0"
description = "API for storing and querying user submitted Japanese journal entries and grammar tags for the Fushigi Kaiwa app."
authors = [
  {name="Tahoe Schrader", email="tahoeschrader@gmail.com"}
]
dependencies = [
  "psycopg2-binary", # connect to postgres
  "tqdm",            # loading screen
  "fastapi",         # create endpoints for database
  "sqlmodel"         # define data model with ORM tool built for FastAPI
]

[project.optional-dependencies]
test = [
    "pydantic",      # validate json
    "pytest",        # tests
    "pytest-cov"     # ensure all code covered by tests
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
